# Generated by Django 2.0.1 on 2020-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinecode', models.CharField(max_length=200, null=True, verbose_name='Machine Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('hourlyrent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Rent')),
                ('max_hours_machine', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Max Hours per day')),
            ],
        ),
    ]
