# Generated by Django 2.0.1 on 2020-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='max_hours_machine',
            field=models.PositiveIntegerField(verbose_name='Max Hours per day'),
        ),
    ]
