# Generated by Django 2.0.1 on 2020-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcode', models.CharField(max_length=200, null=True, verbose_name='Job Code')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('hourlyrate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Rate')),
                ('max_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Max Hours per day')),
            ],
        ),
    ]
