# Generated by Django 2.0.1 on 2020-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_hours',
            field=models.PositiveIntegerField(verbose_name='Max Hours per day'),
        ),
    ]
