# Generated by Django 2.0.1 on 2020-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200324_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='cool', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
