# Generated by Django 2.0.1 on 2020-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitecode', models.CharField(max_length=200, null=True, verbose_name='Site Code')),
                ('contractorName', models.CharField(max_length=200, verbose_name='Contractor Name')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Hours')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Total Amount')),
                ('approved', models.BooleanField(default=False, verbose_name='Approval Status')),
            ],
        ),
    ]
